### ISSUE TITLE
Clicking on "View Replies" yields XHR error

### ISSUE THREAD

**Issue by MrPetovan** [pixelfed/pixelfed#1860]
Post URL: https://pixelfed.mrpetovan.com/p/hypolite/104269765614374912

Tried URLs after clicking on "View Replies": 
- https://pixelfed.mrpetovan.com/api/v2/comments/liaizon/status/106238002304520192
- https://pixelfed.mrpetovan.com/api/v2/comments/johnlitt/status/104276597686800384

Same result:
```json
{
    "message": "No query results for model [App\\Profile]."
}
```

**Comment by dansup** [comment]
Likely a javascript integer overflow, will fix!

**Comment by fedione** [comment]
Is this the same issue?

https://github.com/pixelfed/support/issues/59

**Comment by ghost** [comment]
Is this the same issue?

https://github.com/pixelfed/support/issues/59

**Comment by MrPetovan** [comment]
Yes it is.

**Comment by dansup** [comment]
Looks like the issue is the comments are from a remote profile, working on a fix.

**Comment by dansup** [comment]
@MrPetovan I need more information, I can't reproduce this locally or in [production](https://pixelfed.social/p/dansup/93498629507125248). This may be a deployment issue, are you using postgres or docker?

**Comment by MrPetovan** [comment]
Neither. Manual git install with MariaDB.

**Comment by dansup** [comment]
The pixelfed.social "production" link I shared earlier is now not loading when it was loading before even after page reload. This is a strange bug 😅

**Comment by MrPetovan** [comment]
You're welcome 😊

**Comment by dansup** [comment]
Fixed in latest commits.

**Comment by MrPetovan** [comment]
Yay, thanks!

**Comment by MasterGroosha** [comment]
Not sure if there is a regression or another bug:
Try clicling on "View replies" on https://pixelfed.social/p/Groosha/156192765292711936
You'll see "Error: Request failed with status code 404" in browser console.

**Comment by MasterGroosha** [comment]
Still happens on pixelfed.social, please re-open the issue.
![изображение](https://user-images.githubusercontent.com/2780044/82196978-0e2cf380-9903-11ea-9633-c3906f67fe84.png)
