### ISSUE TITLE
[Postgresql] Hashtag suggestions are case-sensitive

### ISSUE THREAD

**Issue by xundeenergie** [pixelfed/pixelfed#2887]
When i type a hashtag in a new post in caption, i always get "No Match found".

I searched around and found in webserver-logs an api-call on
```
/api/compose/v0/search/hashtag?q=Ago
```

Tried it directly in my browser and there is no result (I have a hashtag, starting with "Ago")

How and where can i enable searching for hashtags? 
I have in my config: 
```
INSTANCE_PUBLIC_HASHTAGS=true
```
to show unauthenticated guests images for my hashtags.

**Comment by xundeenergie** [comment]
look at https://github.com/pixelfed/pixelfed/issues/2888 there are screenshots for my hashtags...

**Comment by xundeenergie** [comment]
it looks like a case-sensitive thing.
The query for hashtags on this endpoint only accept lower-case. my database is postgresql. 
in matrix-chat a guy has no problems with uppercase search. his database is mysql. mine is postgresql.

**Comment by TeknikalDomain** [comment]
I'm the guy. As best as the research I've found, PostgreSQL's `VARCHAR` columns are case-sensitive. My MySQL tables all use the `utf8mb4_unicode_ci` collation, which, given by the `ci`, means **c**ase **i**nsensitive.

[Link to start of message thread in `#pixelfed:matrix.org` for context](https://matrix.to/#/!dSVFUbUBfXIgduyxBO:matrix.org/$163014342010VmZDK:matrix.tdstoragebay.com?via=matrix.org&via=kde.org&via=matrix.tdstoragebay.com)

**Comment by xundeenergie** [comment]
https://github.com/pixelfed/pixelfed/issues/2727

**Comment by dansup** [comment]
Fixed in latest commits!

**Comment by xundeenergie** [comment]
Sorry.... it's not gone.. or do i have to "recreate" the hashtag-list?

I get - after update - no suggestions for upper-case hashtags, which i want to use.

**Comment by xundeenergie** [comment]
i think, i found the solution for case-sensitive/insensitive hashtags... 

i'm working on and with jira and confluence in my worklife... 

And i have to handle many exports and imports via xml-files... and there i saw it many times... but realized it yesterday... 

Confluence saves spacekeys in original case AND lowercase. I could not imagine why. But now i know it. It for search-purpose. Because Confluence supports mssql, mysql, mariadb, sqlite and postgresql as database-backend. And they solved it with lowerkey (they call it exactly this) spacekeys additionally...

And i'm sure... this would be the solution for pixelfed too, to support different databases and have consistent search-result over all backends...

**Comment by xundeenergie** [comment]
Suggestions for hashtags are still missing in webapp... why is this closed?

**Comment by trwnh** [comment]
Cannot reproduce

![image](https://github.com/pixelfed/pixelfed/assets/10606431/4c9bb103-2991-4819-a2ac-5027c57399ac)

**Comment by xundeenergie** [comment]
I use a hastag #Greifenstein (upper case first character)

But no suggestion for upper case... only when i start with lower case... but i want to use CamelCase hashtags for better experience for screenreader-users.

And... i'm german-speaking... we use Uppercase words also in a sentence

**Comment by xundeenergie** [comment]
![IMG_20240531_095955](https://github.com/pixelfed/pixelfed/assets/5894829/6f39c1ec-dd0f-4022-9f64-3345b199da5a)
![IMG_20240531_100025](https://github.com/pixelfed/pixelfed/assets/5894829/a10309a6-0799-4dae-a660-0949b3dc8d7b)

**Comment by trwnh** [comment]
Folding this into #2727 since it cannot be reproduced on mysql but seemingly still affects postgresql
