### ISSUE TITLE
Account Alias / Migration page incomplete/not working

### ISSUE THREAD

**Issue by tzugen** [pixelfed/pixelfed#4858]
On a server running 0.11.9:

1. On my new account I open the "Manage alias" page.
2. I enter my old account in the form
3. The alias is shown correctly
4. "The process of moving the account starts from the old one."
5. I login to the old account.
6. The alias page shows no button etc to start the move.

**Comment by ghost** [comment]
We're running the same version at https://bolha.photos and today an user told me that he tried to move to another server and the process is not working.

**Comment by mitexleo** [comment]
+1

**Comment by mermaid-marina** [comment]
Same problem at https://pixelfed.meerjungfrauengrotte.de

**Comment by Cr4tes** [comment]
I can't see any movement either. I am trying to move from pixelfed.de to pixelfed.social

**Comment by dbrgn** [comment]
I initiated a migration from pixelfed.de to mountains.photos. On pixelfed.de it looks as if it has worked, but the new account still doesn't have any followers or posts and my Mastodon account is still following the old account, not the new one 😕 According to the admin of the target server, the logs don't show anything relevant.

**Comment by gunchleoc** [comment]
Same for me. After initiating the migration away from pixelfed.de, I got the following message:

> You have migrated your account already.
> 
> You can only migrate your account once per 30 days. If you want to migrate your followers back to this account, follow this process in reverse.

This is already confusing as a success message.

Followers are now 0, but I had exported them, so I could manually ping everybody from the new location.

2 days later, no follower has appeared on the new account except for those who followed manually.

pixelfed.de is running  v0.11.13

My new server is running  v0.12.1

.env settings for the new server:

```
# ActivityPub Configuration
ACTIVITY_PUB="true"
AP_REMOTE_FOLLOW="true"
AP_INBOX="true"
AP_OUTBOX="true"
AP_SHAREDINBOX="true"
```

**Comment by dbrgn** [comment]
I gave up. Account migration seems to be entirely broken, even though it's promoted in the documentation 😕 I now have an old, broken acount that I can't really recover, and a new, empty account.

**Comment by HelmutsCab** [comment]
Same here, Migration didn't work, all followers gone.

**Comment by ghost** [comment]
Still not working - tried to move between to instances with latest build. Standard users, no admins - and while the followers disappeared from the old instance, neither those nor > 400 posts appeared on the new one. Still a great mess although it's part of the official documentation - is there any piece of news on the migration status yet?

**Comment by nigini** [comment]
Same here!!! I tried migrating from `pixelfed.social` to `pixelfed.art`. While nothing was migrated to the new account, my followers disappeared from the old account! :(

**Comment by gedankenstuecke** [comment]
Adding to this as it seemed the most relevant existing issue: 

I tried migrating from Pixelfed.de to a mastodon instance (photog.social), and it gets stuck as "Invalid account lookup response", regardless of how long I wait since setting the alias on the new home

**Comment by MarkJaroski** [comment]
So, one of our users tried to migrate from another pixelfed instance a few days ago, and hit this issue.

We're thinking it might be useful for the source instance to retain follower data while this is being implemented, so the follower migration can be retried once the feature is rolled-out.

That means two bits of development:

1. As a priority make sure that follower relationships are maintained somehow, while ...
2. Follower migration is completed

**Comment by arthurcaccavo** [comment]
Just happened to me while trying to migrate from pixelfed.social to gram.social :/

**Comment by andre-dierker** [comment]
This happened to a user while migrating from metapixl.com to pixelfed.art, any updates or workarounds for this?

**Comment by jatardine** [comment]
Not to add more noise but I'm affected by it, as well. Tried migrating from pixelfed.social to lens.im and the only thing that happened was my old account's followers getting removed and the counter being reset to 0. I can't access my unchanged followings, which simply generates an "account moved" error, but I still am able to follow new accounts, accept new followers, like other posts AND even publish new post and comments as if a moved account isn't restricted like a regular account on any Mastodon instance, despite using the same (albeit modified) migration mechanism.

**Comment by xhabih** [comment]
Same here. I think this is a basic feature that should be prioritized, @dansup?

**Comment by herdivineshadow** [comment]
Attempting to migrate from pixelfed.social to pixelfed.scot and looks like it's not working to bring my followers and following over (although I did export those before I started the process, so it I have to follow manually then ok but weird to have the fields available to try it, if it's not ready yet).

**Comment by irf23** [comment]
Encountering this issue...

**Comment by weddige** [comment]
Same here; lost all my followers while trying to migrate my account 😠

**Comment by xhabih** [comment]
@dansup say at mastodon is fixed: https://mastodon.social/@dansup/113955987244950432
I wish he could comment something here..

**Comment by mbirth** [comment]
Similar to @gedankenstuecke, I'm also trying to migrate from pixelfed.social to my own GotoSocial instance. I've added my Pixelfed URI `https://pixelfed.social/users/USERNAME` into my target account's profile. (As a 2nd alias - there's already another one configured there.)

On Pixelfed, when entering the target account as `USERNAME@target.domain`, my Pixelfed password and clicking the "Move Followers" button, I get the same error message:

> Invalid account lookup response.

Looking that up in the source code seems like it's not seeing the alias in the target profile: https://github.com/pixelfed/pixelfed/blob/ccc70240df3009a54c66f4f29e2d0b10998a1b9b/app/Http/Requests/ProfileMigrationStoreRequest.php#L66-L69

**EDIT:** After doing a WebFinger-request manually, it seems like GotoSocial doesn't return any `alsoKnownAs` field.

**EDIT2:** After the WebFinger, Pixelfed tries to query the actual profile. However, my GotoSocial log shows these:

```
timestamp="03/06/2025 22:05:55.765" func=server.init.func2.Logger.19.1 level=INFO latency="261.038µs" userAgent="(Pixelfed/0.12.5; +https://pixelfed.social)" method=GET statusCode=406 path=/users/mbirth clientIP=167.99.145.215 errors="Error #01: no format can be offered for requested Accept header(s) [application/json]; this endpoint offers [application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\" application/activity+json text/html]\n" requestID=6nv9tdwq040000j4q6vg msg="Not Acceptable: wrote 186B"
timestamp="03/06/2025 22:05:56.618" func=server.init.func2.Logger.19.1 level=INFO latency="289.131µs" userAgent="(Pixelfed/0.12.5; +https://pixelfed.social)" method=GET statusCode=406 path=/users/mbirth clientIP=167.99.145.215 errors="Error #01: no format can be offered for requested Accept header(s) [application/json]; this endpoint offers [application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\" application/activity+json text/html]\n" requestID=h5wstdwq040013334a90 msg="Not Acceptable: wrote 186B"
timestamp="03/06/2025 22:05:57.959" func=server.init.func2.Logger.19.1 level=INFO latency="264.927µs" userAgent="(Pixelfed/0.12.5; +https://pixelfed.social)" method=GET statusCode=406 path=/users/mbirth clientIP=167.99.145.215 errors="Error #01: no format can be offered for requested Accept header(s) [application/json]; this endpoint offers [application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\" application/activity+json text/html]\n" requestID=rxz9tdwq04001315grn0 msg="Not Acceptable: wrote 186B"
```

Looks like Pixelfed is querying using `Accept: application/json` whereas GotoSocial rather expects `Accept: application/activity+json` (or `application/ld+json`).

The `->acceptJson()` from the Illuminate Http library is not sufficient, as it seems:

https://github.com/illuminate/http/blob/9ee54a6bdd4d461c837a82feebac461666407f99/Client/PendingRequest.php#L378-L397

Instead, `->accept('application/activity+json')` should be used here:

https://github.com/pixelfed/pixelfed/blob/d926ea99e035e4bf79d14422b02c96ad9801abf5/app/Services/FetchCacheService.php#L53

**EDIT3:** This needs a bit more rework as the `FetchCacheService::getJson()` is used for the WebFinger request (where it must accept `application/json`) and also for the subsequent profile request (where it must accept `application/activity+json`).

**EDIT4:** Doing the profile request, my GotoSocial seems to expect a signed request which Pixelfed isn't doing. Thus, the request is denied and Pixelfed throws the "Invalid account lookup response.".

**Comment by veroandi** [comment]
As with many users, I experienced the loss of all followers from my previous account during the migration process. Consequently, none of these followers appeared in my new instance.
The Pixelfed project should **block** access to this feature, as it is currently not functioning properly and causing users to lose contact with their friends and followers.

**Comment by kvibber** [comment]
I got the same bland "Invalid account lookup response." error today. First trying to migrate from pixelfed.social to a GoToSocial instance. Then, thinking I could use a Mastodon account as an intermediary, the same error trying to migrate to Mastodon.

**Comment by texjoachim** [comment]
Ok, account transfer still broken. :( Pixelfed.de -> Pixelfed.social. Followers gone, account not moved.

**Comment by mbirth** [comment]
It's as if someone wants to _keep_ you and your followers on Pixelfed... 🤔

**Comment by texjoachim** [comment]
But my followers are gone.

**Comment by MarkJaroski** [comment]
> It's as if someone wants to _keep_ you and your followers on Pixelfed... 🤔

Oh come on. Dan has overextended himeself. That's clear. But he's young and that kind of thing happens. I'm absolutely certain that he is well-meaning, and wants you to be able to migrate away. 

Please don't exaggerate the situation. This is a bug, not a nefarious plan.

**Comment by spiezmaestro** [comment]
I agree this is not intentional, but one of the core functionalities of the Fediverse (decentralized and with that the need for migration options) is broken for at least 1.5 years. This is not a "just a bug"-situation anymore.

**Comment by snarfed** [comment]
I'm hitting the `Invalid account lookup response.` error too, on pixelfed.social. That instance fetches and handles Webfinger and AP actors from my instance (bsky.brid.gy) fine, eg when I search for `@snarfed7.bsky.social@bsky.brid.gy`, it finds that user and loads and renders the actor fine.

@mbirth did you conclude in https://github.com/pixelfed/pixelfed/issues/4858#issuecomment-2936543334 that the account migration code uses its own separate code path for fetching AP actors that wrongly uses `Accept: application/json`? Or something else?

**Comment by mbirth** [comment]
@snarfed Haven’t looked at it for a while. But it was using `Accept: application/json` all the time when it should’ve been `application/activity+json` for the profile request (after it’s done with WebFinger). And the profile request wasn’t signed which my GotoSocial didn’t like.

**Comment by snarfed** [comment]
Double checked on my end just now. I got a Webfinger fetch with `Accept: application/json, User-Agent: (Pixelfed/0.12.6; +https://pixelfed.social)`, but no AP actor fetch at all. 🤷

**Comment by gelbphoenix** [comment]
> **EDIT2:** After the WebFinger, Pixelfed tries to query the actual profile. However, my GotoSocial log shows these:
> 
> ```
> timestamp="03/06/2025 22:05:55.765" func=server.init.func2.Logger.19.1 level=INFO latency="261.038µs" userAgent="(Pixelfed/0.12.5; +https://pixelfed.social)" method=GET statusCode=406 path=/users/mbirth clientIP=167.99.145.215 errors="Error #01: no format can be offered for requested Accept header(s) [application/json]; this endpoint offers [application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\" application/activity+json text/html]\n" requestID=6nv9tdwq040000j4q6vg msg="Not Acceptable: wrote 186B"
> timestamp="03/06/2025 22:05:56.618" func=server.init.func2.Logger.19.1 level=INFO latency="289.131µs" userAgent="(Pixelfed/0.12.5; +https://pixelfed.social)" method=GET statusCode=406 path=/users/mbirth clientIP=167.99.145.215 errors="Error #01: no format can be offered for requested Accept header(s) [application/json]; this endpoint offers [application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\" application/activity+json text/html]\n" requestID=h5wstdwq040013334a90 msg="Not Acceptable: wrote 186B"
> timestamp="03/06/2025 22:05:57.959" func=server.init.func2.Logger.19.1 level=INFO latency="264.927µs" userAgent="(Pixelfed/0.12.5; +https://pixelfed.social)" method=GET statusCode=406 path=/users/mbirth clientIP=167.99.145.215 errors="Error #01: no format can be offered for requested Accept header(s) [application/json]; this endpoint offers [application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\" application/activity+json text/html]\n" requestID=rxz9tdwq04001315grn0 msg="Not Acceptable: wrote 186B"
> ```
> 
> Looks like Pixelfed is querying using `Accept: application/json` whereas GotoSocial rather expects `Accept: application/activity+json` (or `application/ld+json`).
> 
> The `->acceptJson()` from the Illuminate Http library is not sufficient, as it seems:
> 
> https://github.com/illuminate/http/blob/9ee54a6bdd4d461c837a82feebac461666407f99/Client/PendingRequest.php#L378-L397
> 
> Instead, `->accept('application/activity+json')` should be used here:
> 
> [pixelfed/app/Services/FetchCacheService.php](https://github.com/pixelfed/pixelfed/blob/d926ea99e035e4bf79d14422b02c96ad9801abf5/app/Services/FetchCacheService.php#L53)
> 
> Line 53 in [d926ea9](/pixelfed/pixelfed/commit/d926ea99e035e4bf79d14422b02c96ad9801abf5)
> 
>  ->acceptJson() 
> **EDIT3:** This needs a bit more rework as the `FetchCacheService::getJson()` is used for the WebFinger request (where it must accept `application/json`) and also for the subsequent profile request (where it must accept `application/activity+json`).

Can someone who can code in PHP maybe write an PR?

**Comment by moan0s** [comment]
@dansup has announced account migration for loops. The optimistic reading is, that this bug will be solved before/as part of this effort.
https://mastodon.social/@dansup/115243261816581757

**Comment by arthurcaccavo** [comment]
> [@dansup](https://github.com/dansup) has announced account migration for loops. The optimistic reading is, that this bug will be solved before/as part of this effort. https://mastodon.social/@dansup/115243261816581757

he ignored this issue and any inquiry about the issue, when not ignoring he told it was not an existing issue. I would first believe that loops implementation won't work instead of that it would be solved here.

**Comment by weddige** [comment]
Does loops even federate by now? AFAIK it's still only dansup's account that is federated.

**Comment by dansup** [comment]
Fixed in #6194
