### ISSUE TITLE
Preview images not showing up since OpenGraph meta tag "og:image" is missing ("og:description" is missing as well)

### ISSUE THREAD

**Issue by steinarb** [pixelfed/pixelfed#5295]
A while back I noticed that previews of pixelfed articles stopped showing up with images when referred to in teams and slack.

I thought the issue was in teams and/or slack, but it seems like if you send a link to an article, like e.g. https://pixelfed.social/p/steinarb/735595713085995153 then the resulting page when it opens has the meta tags "og:site_name", "og:title" and "og:type", but "og:image" is missing.

It would also improve previews to have an "og:description" (which also seems to be missing)

![image](https://github.com/user-attachments/assets/9e894dbc-5f7f-4b1d-b729-a4a22299d446)

**Comment by dansup** [comment]
Fixed!

https://orcascan.com/tools/open-graph-validator?url=https%3A%2F%2Fpixelfed.social%2Fp%2Fdansup%2F740006600011723056

**Comment by steinarb** [comment]
Yey! That was quick! :smile: Thanks!

I have verified that image previews now shows up in teams.  

(No luck in slack yet, but I think that may be a caching issue: that I'm trying pictures slack already thinks it have seen... or something...?)

**Comment by steinarb** [comment]
It worked for a little while (at least when I tested it in teams), but not when I try now, and when looking at the images in web browsers and using the browsers' devtools to look at the HTML structure the "og:image" <meta> tag doesn't seem to be present.

**Comment by strk** [comment]
It's still failing here: https://pixelfed.de/i/web/post/857605493045839231

Which version of Pixelfed contains the fix ?

**Comment by strk** [comment]
I noticed that the tag is returned if I request the page from an anonymous window, should this issue be reopened? Version of the server is 0.12.5
