### ISSUE TITLE
[Bug]: Unable To Follow Hashtags

### ISSUE THREAD

**Issue by DesertLily13** [pixelfed/pixelfed#5877]
### Description

I'm experiencing issues both in the Android app and on Chrome when I search and try to follow additional hashtags. In app, the button blinks like I selected it but doesn't do anything else, and in Chrome; I'll get the spinning symbol like it's loading, but it gets stuck doing it. It keeps trying to load with no success.

### Steps to reproduce

Search any hashtag and try to select the follow option.

### Pixelfed version

1.0.4

### Acknowledgements

Yes

**Comment by aspiringgeek83** [comment]
Confirming same behaviour for my account, on desktop browser (Chrome and Firefox), iOS (1.1.0.1) and Android (1.1.0.1) apps.
Note that I can unfollow hashtags I am currently following but then cannot follow them again.
My account is on pixelfed.social

**Comment by playernotavailable** [comment]
Same here. Follow button does nothing and as a new user it's mildly frustrating that I can't currently curate my feed to more of my interests. Would appreciate being kept in the loop if anyone hears anything.

**Comment by squareclouds** [comment]
same here. for me it seems to be due to a limit of 25 hashtags? if i unfollow one i can follow something else. i am on pixelfed.social and theres no documentation anywhere where it says the max is 25. in the help there only this comment:

You can follow up to 20 hashtags per hour or 100 per day.

which does not apply to me since i have had those 25 hashtags for weeks already.

i hope this is solved soon

**Comment by DesertLily13** [comment]
Update: now using version 1.2.0, and it's still happening 🙃.

**Comment by ajsalminen** [comment]
> same here. for me it seems to be due to a limit of 25 hashtags? if i unfollow one i can follow something else. i am on pixelfed.social and theres no documentation anywhere where it says the max is 25. in the help there only this comment:
> 
> You can follow up to 20 hashtags per hour or 100 per day.
> 
> which does not apply to me since i have had those 25 hashtags for weeks already.
> 
> i hope this is solved soon

This seems accurate, I've also been unable to follow any more hashtags after reaching the total of 25 on pixelfed.social.

**Comment by knandras** [comment]
Present also in IOS 1.3.0.1

Is this something the server instance can limit?

**Comment by veroandi** [comment]
> Present also in IOS 1.3.0.1
> 
> Is this something the server instance can limit?

@DesertLily13 @knandras 

It seems that the limit for how many hashtags a user could follow was reduced from 250 to 25 in this recent commit: https://github.com/pixelfed/pixelfed/commit/5340649d04c7f28901c2e5b8ca76d64a7c8c58ff.
In my database, my user has only 25 hashtags. When I try to follow more, the button keeps loading, but nothing happens. With a second new user, I could follow a hashtag without a problem.

I don't know the reason for this change, but if a user reaches the limit, the button should be disabled, and a message should appear explaining that the limit has been reached, with a link to the settings page where the user can check the hashtags they are following and delete some if necessary.

**Comment by Skivling** [comment]
> hashtags a user could follow was reduced from 250 to 25

I can confirm this, when I have 25 it doesn't let me follow more, after unfollowing some I am able to again.

My suggestion is to increase the limit to 50 (and make it configurable by instance admin) and also implement your suggestion with disabling the button.

**Comment by ajsalminen** [comment]
> > hashtags a user could follow was reduced from 250 to 25
> 
> I can confirm this, when I have 25 it doesn't let me follow more, after unfollowing some I am able to again.
> 
> My suggestion is to increase the limit to 50 (and make it configurable by instance admin) and also implement your suggestion with disabling the button.

Yeah, 25 is really low as a default so at least slightly bumping it up would be good if possible. Making it configurable for sure too. Would be good to know what the reason for the change is since if it would be possible to just make the feature scale better then there might be no need for such usability changes as disabling the button.

**Comment by Skivling** [comment]
There has to be a limit somewhere, and any user who hits that limit should know why.

**Comment by DesertLily13** [comment]
So, I unfollowed some hashtags because I wanted to be able to follow new ones, and I'm still unable to do the latter 🫠.

**Comment by MxL-spec** [comment]
I would be very happy if the limit would be increased, 25 #s  is really not a lot. And yes, it would be good to get informed when the limit is reached.

**Comment by Simon-Laux** [comment]
#6531 asks for an increased limit and also mentions the bug.

So from what I understand the issues here are:
- hashtag follow limit is too low
- the concrete issue is not surfaced to the user, instead they get an endless spinner.
